name: 'Update Go Dependencies'

description: 'Update Go module dependencies'

inputs:
  token:
    required: false
    description: 'GitHub token'
    default: ${{ github.token }}

  base-branch:
    required: true
    description: 'Base branch for PR'
    default: 'main'

  branch-prefix:
    required: false
    description: 'Branch prefix'
    default: 'update-dependencies'

  pr-title:
    required: false
    description: 'Title for the pull request'
    default: 'Update Golang Dependencies'

  commit-message:
    required: false
    description: 'The commit message for the update'
    default: 'Update Golang dependencies'

  auto-merge:
    required: false
    description: 'Whether a successful PR should be automatically merged'
    default: 'false'

  strategy:
    required: false
    description: 'Strategy for updating dependencies (controlled, direct, or everything)'
    default: 'controlled'

runs:
  using: 'composite'
  steps:
    - name: Checkout and setup
      uses: alchemaxinc/composite-toolbox/checkout-and-setup@v1
      with:
        token: ${{ inputs.token }}

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true
        cache-dependency-path: '**/go.sum'

    - name: Update dependencies (controlled)
      if: ${{ inputs.strategy == 'controlled' }}
      shell: bash
      run: |
        go get -t -u ./...
        go mod tidy

    - name: Update dependencies (direct)
      if: ${{ inputs.strategy == 'direct' }}
      shell: bash
      run: |
        go list -m -f '{{if not .Indirect}}{{.Path}}{{end}}' all \
          | xargs -n1 go get -u
        go mod tidy

    - name: Update dependencies (everything)
      if: ${{ inputs.strategy == 'everything' }}
      shell: bash
      run: |
        go list -m -u all \
          | awk '$NF ~ /^\[v/ { v=$NF; gsub(/[\[\]]/, "", v); print $1 "@" v }' \
          | xargs -n1 go get
        go mod tidy

    - name: Check for changes
      id: check_changes
      uses: alchemaxinc/composite-toolbox/check-changes@v1
      with:
        files: 'go.mod go.sum'

    - name: Create Pull Request
      id: open-pr
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: alchemaxinc/composite-toolbox/create-pr@v1
      with:
        token: ${{ inputs.token }}
        base-branch: ${{ inputs.base-branch }}
        branch-prefix: ${{ inputs.branch-prefix }}
        files: 'go.mod go.sum'
        commit-message: ${{ inputs.commit-message }}
        pr-title: ${{ inputs.pr-title }}
        pr-body: |
          # :arrows_counterclockwise: Go Module Dependencies Update

          This pull request automatically updates Go module dependencies to their latest versions.

          ## :gear: Update Strategy

          **Strategy Used:** `${{ inputs.strategy }}`

          - **controlled**: Updates direct dependencies and their transitive dependencies while maintaining version constraints
          - **direct**: Updates only direct dependencies to their latest versions
          - **everything**: Updates all dependencies including indirect ones to their latest versions

          ## :warning: Important Notes

          - :robot: This PR was **automatically generated**
          - :mag: Please **review all changes** carefully before merging
          - :test_tube: Ensure all tests pass and functionality works as expected
          - :books: Check for any breaking changes or release notes for updated modules

          ## :rocket: Next Steps

          1. Review the dependency changes above
          2. Run tests locally or wait for CI/CD to complete
          3. Merge when everything looks good!

          ---

          *Generated by the Go Dependencies Update action* :sparkles:

    - name: Auto-merge Pull Request
      if: inputs.auto-merge == 'true' && steps.open-pr.outcome == 'success'
      uses: alchemaxinc/composite-toolbox/merge-pr@v1
      with:
        token: ${{ inputs.token }}
        merge-method: 'squash'
        pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
