name: 'Update Terraform Dependencies'

description: 'Update Terraform dependencies'

inputs:
  token:
    required: false
    description: 'GitHub token'
    default: ${{ github.token }}

  base-branch:
    required: true
    description: 'Base branch for PR'
    default: 'main'

  branch-prefix:
    required: false
    description: 'Branch prefix'
    default: 'update-dependencies'

  pr-title:
    required: false
    description: 'Title for the pull request'
    default: 'Update Terraform Dependencies'

  commit-message:
    required: false
    description: 'The commit message for the update'
    default: 'Update Terraform dependencies'

  backend-config:
    required: false
    description: 'Backend configuration value to pass to `terraform init -backend-config=<backend-config>` if needed, otherwise ignore'

  var-file-path:
    required: true
    description: 'Location of Terraform variable file (should contain all sensitive values)'

  working-dir:
    required: true
    description: 'Working directory for Terraform'

  auto-merge:
    required: false
    description: 'Whether a successful PR should be automatically merged'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout and setup
      uses: alchemaxinc/composite-toolbox/checkout-and-setup@v1
      with:
        token: ${{ inputs.token }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Baseline initialization
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: |
        if [ -n "${{ inputs.backend-config }}" ]; then
          terraform init -var-file=${{ inputs.var-file-path }} -backend-config="${{ inputs.backend-config }}"
        else
          terraform init -var-file=${{ inputs.var-file-path }}
        fi

    - name: Get current versions
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: terraform version -json > /tmp/terraform_versions.json

    - name: Update Terraform dependencies
      shell: bash
      run: python ${{ github.action_path }}/update_provider_versions.py ${{ inputs.working-dir }} /tmp/terraform_versions.json

    - name: Terraform validate
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: terraform validate

    - name: Terraform fmt
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: terraform fmt -write

    - name: Check for changes
      id: check_changes
      uses: alchemaxinc/composite-toolbox/check-changes@v1

    - name: Create Pull Request
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: alchemaxinc/composite-toolbox/create-pr@v1
      with:
        token: ${{ inputs.token }}
        base-branch: ${{ inputs.base-branch }}
        branch-prefix: ${{ inputs.branch-prefix }}
        files: '.'
        commit-message: ${{ inputs.commit-message }}
        pr-title: ${{ inputs.pr-title }}
        pr-body: |
          # :arrows_counterclockwise: Terraform Dependencies Update

          This pull request automatically updates Terraform provider dependencies to their latest versions.

          ## :warning: Important Notes

          - :robot: This PR was **automatically generated**
          - :mag: Please **review all changes** carefully before merging
          - :test_tube: Ensure all tests pass and functionality works as expected
          - :books: Check for any breaking changes or release notes for updated providers

          ## :rocket: Next Steps

          1. Review the dependency changes above
          2. Run tests locally or wait for CI/CD to complete
          3. Merge when everything looks good!

          ---

          *Generated by the Terraform Dependencies Update action* :sparkles:

    - name: Auto-merge Pull Request
      if: inputs.auto-merge == 'true'
      uses: alchemaxinc/composite-toolbox/merge-pr@v1
      with:
        token: ${{ inputs.token }}
        merge-method: 'squash'
        pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
