name: 'Checkout and Setup'
description: 'Common checkout and git configuration'
inputs:
  token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Configure git
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
