name: 'Update GitHub Actions'

description: 'Update GitHub Actions used in .github workflow files'

inputs:
  token:
    required: false
    description: 'GitHub token'
    default: ${{ github.token }}

  base-branch:
    required: true
    description: 'Base branch for PR'
    default: 'main'

  branch-prefix:
    required: false
    description: 'Branch prefix'
    default: 'update-actions'

  pr-title:
    required: false
    description: 'Title for the pull request'
    default: 'Update GitHub Actions'

  commit-message:
    required: false
    description: 'The commit message for the update'
    default: 'Update GitHub Actions'

  file-glob:
    required: false
    description: 'Glob for workflow files (relative to repo root)'
    default: '.github/**/*.yml'

  prefixes:
    required: false
    description: 'Comma-separated list of action prefixes to include'
    default: 'actions'

  auto-merge:
    required: false
    description: 'Whether a successful PR should be automatically merged'
    default: 'false'

  dry-run:
    required: false
    description: 'Run without creating a PR (for testing purposes)'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout and setup
      if: inputs.dry-run != 'true'
      uses: alchemaxinc/composite-toolbox/checkout-and-setup@v1
      with:
        token: ${{ inputs.token }}

    - name: Setup Python
      uses: actions/setup-python@v5
      env:
        PYTHON_VERSION: '3.14'
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache-dependency-path: ${{ github.action_path }}/requirements.txt

    - name: Install dependencies
      shell: bash
      run: python -m pip install -r ${{ github.action_path }}/requirements.txt

    - name: Update action versions
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        python ${{ github.action_path }}/cli.py \
          --root "$GITHUB_WORKSPACE" \
          --file-glob "${{ inputs.file-glob }}" \
          --prefixes "${{ inputs.prefixes }}"

    - name: Check for changes
      id: check_changes
      if: inputs.dry-run != 'true'
      uses: alchemaxinc/composite-toolbox/check-changes@v1
      with:
        files: '.github'

    - name: Create Pull Request
      id: open-pr
      if: inputs.dry-run != 'true' && steps.check_changes.outputs.has_changes == 'true'
      uses: alchemaxinc/composite-toolbox/create-pr@v1
      with:
        token: ${{ inputs.token }}
        base-branch: ${{ inputs.base-branch }}
        branch-prefix: ${{ inputs.branch-prefix }}
        files: '.github'
        commit-message: ${{ inputs.commit-message }}
        pr-title: ${{ inputs.pr-title }}
        pr-body: |
          # :arrows_counterclockwise: GitHub Actions Update

          This pull request automatically updates GitHub Actions used in `.github` workflows.

          ## :warning: Important Notes

          - :robot: This PR was **automatically generated**
          - :mag: Please **review all changes** carefully before merging
          - :test_tube: Ensure all tests pass and functionality works as expected
          - :books: Check for any breaking changes or release notes for updated actions

          ## :rocket: Next Steps

          1. Review the action changes above
          2. Run tests locally or wait for CI/CD to complete
          3. Merge when everything looks good!

          ---

          *Generated by the GitHub Actions Update action* :sparkles:

    - name: Auto-merge Pull Request
      if: inputs.dry-run != 'true' && inputs.auto-merge == 'true' && steps.open-pr.outcome == 'success'
      uses: alchemaxinc/composite-toolbox/merge-pr@v1
      with:
        token: ${{ inputs.token }}
        merge-method: 'squash'
        pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
