name: Update Go Dependencies

on:
  workflow_call:
    inputs:
      base-branch:
        description: 'Base branch for PR'
        type: string
        required: false
        default: 'develop'

    secrets:
      GITHUB_TOKEN:
        description: 'GitHub token for authentication'
        required: true

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Update Go Dependencies
        uses: ./.github/actions/go-update
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: ${{ github.event.inputs.base-branch }}
