name: 'Update NPM Dependencies'

description: 'Update NPM dependencies using npm-check-updates'

inputs:
  token:
    required: true
    description: 'GitHub token'
    default: ${{ github.token }}

  base-branch:
    required: true
    description: 'Base branch for PR'
    default: 'develop'

  branch-prefix:
    required: true
    description: 'Branch prefix'
    default: 'update-dependencies'

  pr-title:
    required: false
    description: 'Title for the pull request'
    default: 'Update NPM Dependencies'

  commit-message:
    required: false
    description: 'The commit message for the update'
    default: 'Update NPM dependencies'

  excluded-packages:
    required: false
    description: 'Packages to exclude from updates, in a comma-separated list format'

runs:
  using: 'composite'
  steps:
    - name: Checkout and setup
      uses: alchemaxinc/composite-toolbox/checkout-and-setup@v1
      with:
        token: ${{ inputs.token }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        node-version-file: '.nvmrc'

    - name: Cache npm-check-updates
      id: cache-ncu
      uses: actions/cache@v4
      with:
        path: ~/.npm-global
        key: npm-ncu-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-ncu-${{ runner.os }}-

    - name: Install npm-check-updates
      if: steps.cache-ncu.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npm config set prefix '~/.npm-global'
        export PATH=~/.npm-global/bin:$PATH
        npm install -g npm-check-updates

    - name: Update dependencies
      shell: bash
      run: |
        export PATH=~/.npm-global/bin:$PATH
        if [ -n "${{ inputs.excluded-packages }}" ]; then
          ncu -u --reject "${{ inputs.excluded-packages }}"
        else
          ncu -u
        fi
        npm install

    - name: Check for changes
      id: check_changes
      uses: alchemaxinc/composite-toolbox/check-changes@v1
      with:
        files: 'package.json package-lock.json'

    - name: Create Pull Request
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: alchemaxinc/composite-toolbox/create-pr@v1
      with:
        token: ${{ inputs.token }}
        base-branch: ${{ inputs.base-branch }}
        branch-prefix: ${{ inputs.branch-prefix }}
        files: 'package.json package-lock.json'
        commit-message: ${{ inputs.commit-message }}
        pr-title: ${ inputs.pr-title }
        pr-body: |
          # :arrows_counterclockwise: NPM Dependencies Update

          This pull request automatically updates NPM dependencies to their latest versions.

          ## :warning: Important Notes

          - :robot: This PR was **automatically generated**
          - :mag: Please **review all changes** carefully before merging
          - :test_tube: Ensure all tests pass and functionality works as expected
          - :books: Check for any breaking changes in the updated dependencies

          ## :rocket: Next Steps

          1. Review the dependency changes above
          2. Run tests locally or wait for CI/CD to complete
          3. Merge when everything looks good!

          ---

          *Generated by the NPM Dependencies Update action* :sparkles:
